


select* from ['Online Retail$']

--QUESTION 1
--customer segementation by purchase frequent
--(a) group customers based on their purchase frequency (e.g, one-time, repeat, and high frequently buyer)


select CustomerID,
	COUNT(*) as purchase_count,
	CASE
		when COUNT(*) = 1 THEN 'one-time buyer'
		when COUNT(*) BETWEEN 2 AND 5 THEN 'repeat buyer'
		else 'high-frequency buyer'
	END AS buyer_type
from ['Online Retail$']
group by CustomerID;

--(b) provide insights into how much revenue is generated from segement and suggest potential engagement strategies

select InvoiceNo, 
	Description, 
	CustomerID, 
	Country,
	sum(Quantity*UnitPrice) as Revenue
from ['Online Retail$']
group by InvoiceNo, Description,CustomerID,Country
order by Revenue DESC;

--QUESTION 2
--top 10 most purchase product
--(a) identify the top 10 most purchase products based on total quantity sold

select TOP 10 StockCode,
	SUM(Quantity) as total_quantity_sold
from ['Online Retail$']
group by StockCode
order by total_quantity_sold DESC;
	
--(b) provide a breakdown of which country purchase these product the most 

select TOP 10
	Description,
	Country,
	SUM(quantity) as total_quantity_sold
from ['Online Retail$']
group by Description, Country
order by total_quantity_sold DESC;

--QUESTION 3
--revenue analysis by country 
--(a) calculate total sales revenue for each country, identify the top 5 countries that contribute the most to overall sales.

select TOP 5 Country, SUM(Quantity) as total_sales_revenue
from ['Online Retail$']
group by Country
order by total_sales_revenue DESC;

--(b) provide insight into customer behavior in these country and suggest opportunity for market expansion

select TOP 5 Country,
	COUNT(*) as customer_behavior,
		CASE
			WHEN COUNT(*) = 38 THEN 'AVERAGE'
			WHEN COUNT(*) BETWEEN 500 AND 1000 THEN 'GOOD'
			else 'VERY GOOD'
		END AS Country_Grades
from ['Online Retail$']
group by Country;

--QUESTION 4
--Monthly sales performance 
--(a) analysis monthly sales data to identify the seasonal trends and key period of high or low sales 

select format (InvoiceDate,'MMMM') as Sales_Month,
	SUM(Quantity) as Total_Sales 
from ['Online Retail$']
group by format (InvoiceDate,'MMMM')
order by Sales_Month;

--(b) provide recommendaions on how to capitalize on peak seasons or improve sales on during slower month

--QUESTION 5
--customers lifetime and value (CLV) analysis;
--(a) calculate the customer lifetime and value (CLV) by analysis the total revenue generated by repeat customers over the data's time span

select CustomerID,
	ROUND(SUM(Quantity*UnitPrice),2) as Total_Revenue
from ['Online Retail$']
group by CustomerID
order by Total_Revenue DESC;

--(b) identify the top 5 customers based on total sales value and provide an analysis of their purchasing behaivour( e.g preferred products, purchasing freqency).

select TOP 5 CustomerID,
	ROUND(SUM(Quantity*UnitPrice),2) as Total_Revenue,
	CASE
		when COUNT(*) = 1 THEN 'PREFERRED PRODUCTS'
		WHEN COUNT(*) BETWEEN 3 AND 5 THEN 'PURCHASE FREQUENCY'
		ELSE 'HIGH PURCHASE'
	END AS CUSTOMER_BEHAVIOUR
from ['Online Retail$']
group by CustomerID
order by Total_Revenue DESC;

--QUESTION 6
--Product performance analysis by category(if available)
--(a) analysis which product category(if categories can be derive from description or stockcodes) generate the most sales revenue 

select Description,
	COUNT(*) AS Product_Categories,
	CASE
		WHEN DESCRIPTION like '% BLUE%' THEN 'BLUES'
		WHEN DESCRIPTION like '% CREAM%' THEN 'CREAMS'
		WHEN DESCRIPTION like '% ROSE%' THEN 'ROSES'
		WHEN DESCRIPTION like '% GREEN%' THEN 'GREENS'
	ELSE 'OTHERS'
	END AS Product_Categories,ROUND(SUM(Quantity*Unitprice),2) as Total_Revenue
from ['Online Retail$']
group by Description 
order by Total_Revenue DESC;

--(b) provide insights into product trends and suggest which categories should be prioritised for sales and marketting efforts
